#!/usr/bin/env python3
"""Render the immutable v2 direct-10K pre-dispatch failure report."""
import html, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'milestones/m2-8-direct-10k-attempt-v2.json'
OUT = ROOT / 'milestones/m2-8-direct-10k-attempt-v2.html'
e = json.loads(DATA.read_text())
esc = html.escape
html_doc = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(e['milestone'])}</title><style>
:root{{--ink:#172733;--muted:#566b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--red:#8a3327;--redbg:#fff0ed;--blue:#0b5e8d}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:var(--blue)}}.wrap{{max-width:1080px;margin:22px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(120deg,#fff 54%,#fff2ef)}}h1{{font-size:clamp(1.8rem,4vw,2.5rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.badge{{display:inline-block;background:var(--redbg);color:var(--red);padding:5px 12px;border-radius:99px;font-weight:750}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:#fff;border:1px solid var(--line);border-radius:99px;padding:6px 11px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}}.metric b{{display:block;font-size:1.2rem}}.metric span{{color:var(--muted);font-size:.9rem}}.call{{border-left:4px solid var(--red);background:var(--redbg);padding:13px 16px}}table{{border-collapse:collapse;width:100%;min-width:650px}}.scroll{{overflow:auto;border:1px solid var(--line);border-radius:10px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code{{font-family:ui-monospace,monospace;background:#f0f4f6;padding:2px 4px;border-radius:4px;overflow-wrap:anywhere}}.cols{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}footer{{color:var(--muted);padding:10px 4px 24px;font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}.cols{{grid-template-columns:1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">{esc(e['milestone'])} · {esc(e['snapshot_time'])}</p><span class="badge">作业失败 · 0 次群体调用</span><h1>GPU08 与模型已启动，驱动在首个请求前失败</h1><p>{esc(e['outcome'])}</p><nav aria-label="报告导航"><a href="#evidence">调度证据</a><a href="#cause">故障原因</a><a href="#fix">修复与重跑</a><a href="#limits">研究边界</a></nav></header>
<div class="grid"><div class="metric"><b>235412 · FAILED</b><span>18 分 02 秒；ExitCode 1:0</span></div><div class="metric"><b>8 × H20</b><span>GPU08 独占分配</span></div><div class="metric"><b>48 / 48</b><span>模型分片加载完成</span></div><div class="metric"><b>0 / 21,002</b><span>请求未派发</span></div></div>
<section id="evidence"><h2>用户要求与实测</h2><div class="scroll"><table><thead><tr><th>用户要求</th><th>实施</th><th>实际证据</th><th>结论</th></tr></thead><tbody><tr><td>直接测试 10K 群体</td><td>10,000 分析 Agent + 501 治理角色，两轮</td><td>Slurm 作业启动，模型 API 没有收到请求；群体事件库和预算库均未创建</td><td>群体执行未开始</td></tr><tr><td>使用 GPU08 与本地 DeepSeek</td><td>GPU08 上申请 8 张 H20，模型仅监听回环</td><td>48/48 分片加载；08:06:11 应用启动；08:06:57 health 返回 200</td><td>模型 serving 启动通过</td></tr><tr><td>可追溯并保留失败</td><td>唯一运行目录、源码 archive、日志、Slurm 记录</td><td>Job 235412 FAILED；完整 Python traceback 留在受限群集目录</td><td>失败作为原始证据保留</td></tr></tbody></table></div></section>
<section id="cause"><h2>根因定位</h2><p>驱动构造第一批消息时调用 <code>AutoTokenizer.apply_chat_template()</code>，随后因 <code>tokenizer.chat_template</code> 为空退出。该检查点没有 Hugging Face 模板；SGLang v0.5.16 对 DSV4 使用自身的 <code>encoding_dsv4.encode_messages()</code> 渲染，再调用 tokenizer 编码。它在运行时启动后、claim/请求派发前失败。</p><div class="call"><b>观测事实：</b>群集目录中仅有 <code>population.json</code>；没有 journal.sqlite、budget.sqlite、attempt receipt 或请求响应。计划 21,002 次，实际派发 0 次。</div><p>此次消耗一个 18:02 的 GPU08 作业窗口，其中模型加载与 warmup 完成，但未产生模型推理。此开销作为工程负结果保留。</p><ul><li><a href="https://github.com/sgl-project/sglang/blob/v0.5.16/python/sglang/srt/entrypoints/openai/encoding_dsv4.py">SGLang v0.5.16 DSV4 encoder</a></li><li><a href="https://github.com/sgl-project/sglang/blob/v0.5.16/python/sglang/srt/entrypoints/openai/serving_chat.py">SGLang v0.5.16 serving path</a></li></ul></section>
<section id="fix"><h2>下一次运行的修复与身份</h2><div class="cols"><div><h3>修复</h3><ul><li>在相同容器内复用内置 DSV4 message encoder，按准确服务格式对输入 token 计数。</li><li>冻结 <code>thinking_mode=thinking</code>，请求明确传 <code>chat_template_kwargs.thinking=true</code>。</li><li>增加针对缺模板检查与原生 encoder 的单元测试。</li></ul></div><div><h3>当前验证</h3><ul><li>102/102 仓库测试通过。</li><li>新版本 v4 配置与 batch 脚本已准备。</li><li>截至本报告快照，v4 尚未提交；该报告不宣称修复已在 GPU 上验证。</li></ul></div></div></section>
<section id="limits"><h2>科学解释与边界</h2><p><b>数学结论：</b>没有数学输出；未完成 Navier–Stokes 证明或反证评价。</p><p><b>群体效果：</b>没有可用于群体效果分析的观测；失败不是一次已初始化的 population run。</p><p><b>下一门槛：</b>用新 source commit 与 population ID 提交 GPU08 v4；核对启动、实际调用计数、回执/预算记录与首个完整阶段。仍不要求单 Agent 先解题，也不把模型一致性作为数学验证。</p><p><b>本次源码基线：</b><code>{esc(e['source_baseline_commit'])}</code> · <b>模型镜像：</b><code>{esc(e['model']['container_sha256'])}</code></p></section><footer>v3 的 Slurm、server 与 population 日志保存在院内受限 run root；本页面记录可公开的脱敏证据。此前启动快照见 <a href="m2-8-direct-10k-launch-v1.html">v1 HTML</a>。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{let n=document.querySelector(a.getAttribute('href'));if(n)n.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
OUT.write_text(html_doc)
print(OUT)
