#!/usr/bin/env python3
"""Render the v5 GPU08 direct-10K output-truncation report."""
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; e=json.loads((ROOT/'milestones/m2-8-direct-10k-gpu08-v5-attempt-v1.json').read_text())
H=html.escape
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GPU08 10K 群体运行 v5：输出截断</title><style>
:root{{--ink:#172733;--muted:#566b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--red:#8a3327;--redbg:#fff0ed;--blue:#0b5e8d}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:var(--blue)}}.wrap{{max-width:1080px;margin:22px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(120deg,#fff 54%,#fff2ef)}}h1{{font-size:clamp(1.8rem,4vw,2.5rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.badge{{display:inline-block;background:var(--redbg);color:var(--red);padding:5px 12px;border-radius:99px;font-weight:750}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:#fff;border:1px solid var(--line);border-radius:99px;padding:6px 11px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}}.metric b{{display:block;font-size:1.2rem}}.metric span{{color:var(--muted);font-size:.9rem}}.call{{border-left:4px solid var(--red);background:var(--redbg);padding:13px 16px}}table{{border-collapse:collapse;width:100%;min-width:680px}}.scroll{{overflow:auto;border:1px solid var(--line);border-radius:10px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code{{font-family:ui-monospace,monospace;background:#f0f4f6;padding:2px 4px;border-radius:4px;overflow-wrap:anywhere}}.cols{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}footer{{color:var(--muted);padding:10px 4px 24px;font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}.cols{{grid-template-columns:1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">M2.8 · 2026-10-01 · 10K 人口直接运行 · v5 运行记录</p><span class="badge">16 次 HTTP 200 · 0 个可用 final</span><h1>超时问题已解决，1,024-token 上限截断全部首批回答</h1><p>600 秒超时下，DeepSeek-V4-Flash-0731 返回了 16 个 HTTP 200 响应并记录 usage。每个响应都以 <code>finish_reason=length</code> 用满 1,024 completion tokens，但 visible final content 长度为 0；驱动触发缺少 final content 停止条件。</p><nav aria-label="报告导航"><a href="#mapping">要求与证据</a><a href="#result">运行结果</a><a href="#recovery">事件恢复</a><a href="#next">下一版设计</a></nav></header>
<div class="grid"><div class="metric"><b>235506 · COMPLETED</b><span>应用受控停止 · 06:34</span></div><div class="metric"><b>8 × H20</b><span>GPU08 独占分配</span></div><div class="metric"><b>16 / 21,002</b><span>已结算 / 计划调用</span></div><div class="metric"><b>0 / 9,984</b><span>final content / 未尝试 worker</span></div></div>
<section id="mapping"><h2>用户要求、实现与实测证据</h2><div class="scroll"><table><thead><tr><th>要求</th><th>实施</th><th>实测证据</th><th>边界</th></tr></thead><tbody><tr><td>直接执行 10K，不以前置单 Agent 成功为条件</td><td>10,000 worker + 501 治理角色，两轮 21,002 调用槽位</td><td>完整人口驱动已初始化；16 个 worker 请求均结算</td><td>首个 worker phase 后停止；9,984 worker 与所有治理角色未尝试</td></tr><tr><td>GPU08 全部 H20 + 本地 DeepSeek</td><td>独占 8×H20；SGLang loopback 端点；600 秒 timeout</td><td>48/48 分片；health=200；16 个 Chat Completions HTTP 200</td><td>所有输出达到长度上限，未提供可用 final content</td></tr><tr><td>可追溯、可恢复</td><td>事件 journal、预算 ledger、每五分钟 rolling checkpoint</td><td>两代 checkpoint；16 份 receipts；SQLite integrity_check=ok</td><td>原始正文只留院内私有目录，不向 GitHub 发布</td></tr></tbody></table></div></section>
<section id="result"><h2>人口和服务结果</h2><p>Job <code>235506</code> 运行于 GPU08，分配 8 张 H20、224 个 CPU，6 分 34 秒后应用受控停止。SGLang health 返回 200；服务端第一批 16 请求最终均为 HTTP 200。</p><div class="call"><b>直接观测：</b>16/16 的 <code>finish_reason=length</code>，每个 <code>completion_tokens=1024</code>；16 个 <code>message.content</code> 均为空字符串。输入 7,673、输出 16,384、总计 24,057 tokens，Usage 全部已知。v4 的 120 秒超时被纠正；第一批在 generation 开始约 133 秒后返回，超过旧客户端窗口。</div><p>应用摘要：<code>halt_reason=missing_final_content</code>；worker 已尝试 16/10,000；尚余9,984 worker；501 observer/chief/global 角色未开始。没有数学答案、证明、反证或架构效果证据。</p></section>
<section id="recovery"><h2>恢复与完整性证据</h2><ul><li>五分钟 sidecar 已写出两代一致 SQLite 备份，并把 receipts 复制到权限受限的共享 run root。</li><li>最新 checkpoint：<code>{H(e['evidence']['latest_checkpoint'])}</code>；16 receipts；Journal 完整性：<code>ok</code>。</li><li>Checkpoint manifest SHA-256：<code>{H(e['evidence']['checkpoint_manifest_sha256'])}</code>。</li><li>Checkpoint journal SHA-256：<code>{H(e['evidence']['checkpoint_journal_sha256'])}</code>。</li><li>源码 commit：<code>{H(e['source_commit'])}</code>；源码归档 SHA-256：<code>{H(e['source_archive_sha256'])}</code>；镜像 SHA-256：<code>{H(e['model']['container_sha256'])}</code>。</li></ul><p>这是工程失败记录，不是独立 population replicate。v4 和 v5 共用组织、数学任务和模型部署条件；二者任何一方都不能支持 Agent 架构优越性判断。</p></section>
<section id="next"><h2>下一版输出与时限配置</h2><p>本次完成调用表明需要给可见 final 留出 token 空间。已冻结的 v6 工程配置将输出上限提高到 4,096 tokens、请求超时提高到 1,200 秒、人口期限提高到 160 小时；仍为同一 10K roster、两轮、16 并发、DeepSeek-V4 reasoning mode，使用新的 run ID。160 小时作业计划在 `Res_libs` 10 月 8 日截止前完成。</p><p><b>这是待检验的配置假设。</b>若 v6 仍以 length 截断或超出服务吞吐可行预算，应保留失败并据真实时延调整，不能将 missing output 修复成成功。</p><p><b>就绪度：</b>组织设计保持；新工程配置已实现；v6 仍须验证首个有内容的 final、rolling checkpoint 和分轮进展。所有数学内容仍需独立 proof obligations 审核。</p></section><footer>快照：{H(e['snapshot_time'])} · 取证目录：院内权限受限存储。模型响应正文与潜在 reasoning 不在公共页面。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{let n=document.querySelector(a.getAttribute('href'));if(n)n.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
(ROOT/'milestones/m2-8-direct-10k-gpu08-v5-attempt-v1.html').write_text(page);print(ROOT/'milestones/m2-8-direct-10k-gpu08-v5-attempt-v1.html')
