#!/usr/bin/env python3
"""Render the v6 GPU08 direct-10K attempt report."""
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];e=json.loads((ROOT/'milestones/m2-8-direct-10k-gpu08-v6-attempt-v1.json').read_text());H=html.escape
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GPU08 10K 群体运行 v6：输出仍被截断</title><style>
:root{{--ink:#172733;--muted:#566b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--red:#8a3327;--redbg:#fff0ed;--blue:#0b5e8d}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:var(--blue)}}.wrap{{max-width:1080px;margin:22px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(120deg,#fff 54%,#fff2ef)}}h1{{font-size:clamp(1.8rem,4vw,2.5rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.badge{{display:inline-block;background:var(--redbg);color:var(--red);padding:5px 12px;border-radius:99px;font-weight:750}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:#fff;border:1px solid var(--line);border-radius:99px;padding:6px 11px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}}.metric b{{display:block;font-size:1.2rem}}.metric span{{color:var(--muted);font-size:.9rem}}.call{{border-left:4px solid var(--red);background:var(--redbg);padding:13px 16px}}table{{border-collapse:collapse;width:100%;min-width:680px}}.scroll{{overflow:auto;border:1px solid var(--line);border-radius:10px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code{{font-family:ui-monospace,monospace;background:#f0f4f6;padding:2px 4px;border-radius:4px;overflow-wrap:anywhere}}.cols{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}footer{{color:var(--muted);padding:10px 4px 24px;font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}.cols{{grid-template-columns:1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">M2.8 · 2026-10-01 · 10K 人口直接运行 · v6 运行记录</p><span class="badge">16 个 HTTP 200 · 1 份可见截断文本</span><h1>2,048-token cap 只产生 1 份可见文本，群体仍停止</h1><p>v6 的服务在 DeepGEMM 首次 JIT 编译后健康启动。16 个首批 worker 请求均返回 HTTP 200，均以 <code>finish_reason=length</code> 达到 2,048 tokens；15 个 final 内容为空，另 1 个为 2,369 字符的截断文本。</p><nav aria-label="报告导航"><a href="#mapping">要求与证据</a><a href="#result">运行结果</a><a href="#recovery">恢复证据</a><a href="#next">下一版配置</a></nav></header>
<div class="grid"><div class="metric"><b>235507 · COMPLETED</b><span>应用受控停止 · 18:31</span></div><div class="metric"><b>8 × H20</b><span>GPU08 独占分配</span></div><div class="metric"><b>16 / 21,002</b><span>已结算 / 计划调用</span></div><div class="metric"><b>1 / 9,984</b><span>部分文本 / 未尝试 worker</span></div></div>
<section id="mapping"><h2>用户要求、实施与实测证据</h2><div class="scroll"><table><thead><tr><th>要求</th><th>实施</th><th>实测证据</th><th>边界</th></tr></thead><tbody><tr><td>直接上 10K；无单 Agent 前置成功门槛</td><td>10,000 worker + 501 治理角色；两轮 21,002 槽位</td><td>完整人口配置初始化，首批16个 worker 请求结算</td><td>9,984 worker 和所有治理角色未开始</td></tr><tr><td>用 GPU08 全部 H20 和本地 DeepSeek</td><td>独占8×H20、loopback SGLang、2048-token cap、1200秒 timeout</td><td>48/48 分片；health=200；服务端16个 HTTP 200</td><td>全部为 length 终止，只有一份 partial text</td></tr><tr><td>事件可溯源、断点恢复</td><td>node-local journal 加五分钟 rolling copy</td><td>16 receipts、两个 checkpoint generation、SQLite integrity=ok</td><td>只是一轮失败记录，不是独立群体复现</td></tr></tbody></table></div></section>
<section id="result"><h2>群体与模型响应</h2><p>Slurm 235507 在 GPU08 分配 8×H20、224 CPU，运行18分31秒，作业本身正常结束，应用因 <code>missing_final_content</code> 受控停止。Usage 已知：7,673 输入 + 32,768 输出 = 40,441 tokens；无未知 usage。</p><div class="call"><b>逐回执核验：</b>16/16 <code>finish_reason=length</code>，每份恰好2,048 completion tokens；15份 <code>message.content</code> 为空。仅1份有可见文本（2,369字符），但也以 length 结束，且不是有效 JSON。因此它是截断输出，不计作完成答案。</div><p>轮次只完成失败的首个 worker phase；9,984 worker 未尝试，501 governance roles 未启动。没有数学证明/反证评价，也没有组织优越性结论。</p></section>
<section id="recovery"><h2>检查点与身份</h2><ul><li>五分钟 sidecar 保留两个滚动 generation；最新点 <code>{H(e['evidence']['latest_checkpoint'])}</code>，包含16 receipts。</li><li>SQLite <code>integrity_check=ok</code>；journal SHA-256 <code>{H(e['evidence']['checkpoint_journal_sha256'])}</code>。</li><li>checkpoint manifest SHA-256 <code>{H(e['evidence']['checkpoint_manifest_sha256'])}</code>；latest pointer SHA-256 <code>{H(e['evidence']['latest_pointer_sha256'])}</code>。</li><li>源码 commit <code>{H(e['source_commit'])}</code>；source archive SHA-256 <code>{H(e['source_archive_sha256'])}</code>；容器 SHA-256 <code>{H(e['model']['container_sha256'])}</code>。</li></ul><p>原始回执和文本留在院内权限受限目录，公共报告只含结构化统计与哈希。</p></section>
<section id="next"><h2>下一版输出预算</h2><p>v6 从2,048-token cap 取得一份 partial text，仍无法形成完整 worker phase。v7 冻结3,072-token response cap、1,200秒请求 timeout、16并发、165小时 population deadline，并保持相同10K组织、模型、任务和 reasoning mode。计划完成时间在 `Res_libs` 预约结束前。</p><p>这是下一次待证伪/支持的工程假设。若继续 length 截断，应记录新失败，不把 partial content提升为数学结论。</p><p><b>就绪度：</b>10K组织设计继续冻结；v7运行配置已实现；数学验证和组织效果结论仍未就绪。</p></section><footer>快照：{H(e['snapshot_time'])} · v4、v5、v6 是连续工程配置尝试，不能合并成独立 population replicates。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{let n=document.querySelector(a.getAttribute('href'));if(n)n.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
(ROOT/'milestones/m2-8-direct-10k-gpu08-v6-attempt-v1.html').write_text(page);print(ROOT/'milestones/m2-8-direct-10k-gpu08-v6-attempt-v1.html')
