#!/usr/bin/env python3
"""Render a timestamped live v8 GPU08 direct-10K snapshot."""
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
e=json.loads((ROOT/'milestones/m2-8-direct-10k-gpu08-v8-live-v1.json').read_text())
H=html.escape
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GPU08 10K v8：chat 模式运行中</title><style>
:root{{--ink:#172733;--muted:#566b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--green:#17664c;--greenbg:#eaf7f0;--blue:#0b5e8d}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:var(--blue)}}.wrap{{max-width:1080px;margin:22px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(120deg,#fff 55%,#eaf7f0)}}h1{{font-size:clamp(1.8rem,4vw,2.5rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.badge{{display:inline-block;background:var(--greenbg);color:var(--green);padding:5px 12px;border-radius:99px;font-weight:750}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:#fff;border:1px solid var(--line);border-radius:99px;padding:6px 11px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}}.metric b{{display:block;font-size:1.2rem}}.metric span{{color:var(--muted);font-size:.9rem}}.call{{border-left:4px solid #bb7821;background:#fff8e9;padding:13px 16px}}table{{border-collapse:collapse;width:100%;min-width:680px}}.scroll{{overflow:auto;border:1px solid var(--line);border-radius:10px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code{{font-family:ui-monospace,monospace;background:#f0f4f6;padding:2px 4px;border-radius:4px;overflow-wrap:anywhere}}footer{{color:var(--muted);padding:10px 4px 24px;font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">M2.8 · 2026-10-01 · 10K 人口直接运行 · v8 实时快照</p><span class="badge">235511 RUNNING · chat / thinking=false</span><h1>首批 34 份回执全部被运行时接纳</h1><p>在保持完整 10K 群体与 GPU08 八卡的前提下，v8 切换到 DSV4 chat 模式。当前 34/34 回执均为非空且以 <code>finish_reason=stop</code> 结束；其中28份可解析为提示要求的五字段 JSON，6份格式不符。群体仍在首个 worker 阶段。</p><nav aria-label="报告导航"><a href="#mapping">要求与实施</a><a href="#progress">实时结果</a><a href="#recovery">检查点身份</a><a href="#next">限制与下一步</a></nav></header>
<div class="grid"><div class="metric"><b>235511 · RUNNING</b><span>GPU08 · 8 × H20 · 224 CPU</span></div><div class="metric"><b>34 / 10,000</b><span>运行时接纳 / analysis workers</span></div><div class="metric"><b>28 / 34</b><span>五字段 JSON 可解析</span></div><div class="metric"><b>9,950 + 16</b><span>待运行 + 正在运行 workers</span></div></div>
<section id="mapping"><h2>用户要求、实施与当前证据</h2><div class="scroll"><table><thead><tr><th>要求</th><th>实施</th><th>当前实测</th><th>尚未证明</th></tr></thead><tbody><tr><td>直接启动10K，不设单 Agent 成功门槛</td><td>10,000 worker、501 governance、两轮21,002槽位</td><td>完整人口初始化；首阶段34份回执</td><td>9,950 workers待运行；治理阶段未开始</td></tr><tr><td>GPU08全卡，本地DeepSeek</td><td>8×H20；固定本地模型；loopback SGLang；chat模式</td><td>48/48分片；健康检查200；34份 stop final</td><td>总体运行表现、长程稳定性</td></tr><tr><td>科学和 AI 输出格式可追踪</td><td>SQLite事件日志、角色输出字段、回执校验</td><td>34运行时接纳；28份符合五字段JSON键集</td><td>6份无效/非JSON；数学证明与治理链均未核验</td></tr></tbody></table></div></section>
<section id="progress"><h2>首批回执与 usage</h2><p>截至10:21，worker 步骤状态为34 succeeded、16 running、9,950 pending，失败项为0。34份回执均有已知 usage：16,304输入 + 36,306输出 = 52,610 tokens；SQLite 实时完整性检查为 <code>ok</code>。</p><div class="call"><b>区分运行时和格式验收：</b>运行时目前只要求 final content 非空且 <code>finish_reason=stop</code>，并不强制 JSON 解析。对已接纳内容另行审计发现28份有提示要求的五个键，6份无法解析为该 JSON 结构。所有数学候选仍未验证。后续报告将保留这两个质量层级。</div><p>v7 的对照条件为 thinking 模式下16份均 length 截断；v8 当前早期数据支持“chat模式更易产出stop final”的工程假设，但样本只有34份且运行进行中，不能据此认定数学能力或 Agent 架构改善。</p></section>
<section id="recovery"><h2>检查点与版本身份</h2><ul><li>node-local live journal 已有34份 receipt；最新滚动检查点 <code>{H(e['evidence']['latest_checkpoint'])}</code> 也含34份，SQLite <code>integrity_check=ok</code>。</li><li>Journal SHA-256 <code>{H(e['evidence']['latest_checkpoint_journal_sha256'])}</code>；checkpoint manifest SHA-256 <code>{H(e['evidence']['checkpoint_manifest_sha256'])}</code>；latest pointer SHA-256 <code>{H(e['evidence']['latest_pointer_sha256'])}</code>。</li><li>源码 commit <code>{H(e['source_commit'])}</code>；archive SHA-256 <code>{H(e['source_archive_sha256'])}</code>；配置 SHA-256 <code>{H(e['config_sha256'])}</code>。</li><li>模型容器 SHA-256 <code>{H(e['model']['container_sha256'])}</code>；模型配置 SHA-256 <code>{H(e['model']['model_config_sha256'])}</code>。原始响应保持在集群受限路径。</li></ul></section>
<section id="next"><h2>下一阶段状态</h2><p>继续让冻结的10K人口跑 worker 阶段；监控新增回执、JSON有效比例、重启恢复副本和是否进入 observer/chief。不得把有效 JSON、运行时接纳或群体共识当成证明。正式数学评价仍需独立检查假设、逻辑链、证明依赖和反例条件。</p><p><b>就绪度：</b>10K 调度和 chat-mode 内容链正在实跑；JSON结构完整率尚非100%；治理层、数学验证、独立人口比较尚未就绪。</p></section><footer>快照：{H(e['snapshot_time'])} · v8仍在运行；这是启动阶段快照，不代表最终10K结果。单一响应不能说明群体能力。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{let n=document.querySelector(a.getAttribute('href'));if(n)n.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
(ROOT/'milestones/m2-8-direct-10k-gpu08-v8-live-v1.html').write_text(page)
print(ROOT/'milestones/m2-8-direct-10k-gpu08-v8-live-v1.html')
