#!/usr/bin/env python3
"""Render the v4 GPU08 10K transport-timeout attempt report."""
import html,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
e=json.loads((ROOT/'milestones/m2-8-direct-10k-gpu08-v4-attempt-v1.json').read_text()); esc=html.escape
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GPU08 10K 群体运行 v4：超时中止</title><style>
:root{{--ink:#172733;--muted:#566b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--red:#8a3327;--redbg:#fff0ed;--blue:#0b5e8d}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:var(--blue)}}.wrap{{max-width:1080px;margin:22px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(120deg,#fff 54%,#fff2ef)}}h1{{font-size:clamp(1.8rem,4vw,2.5rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.badge{{display:inline-block;background:var(--redbg);color:var(--red);padding:5px 12px;border-radius:99px;font-weight:750}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:#fff;border:1px solid var(--line);border-radius:99px;padding:6px 11px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}}.metric b{{display:block;font-size:1.2rem}}.metric span{{color:var(--muted);font-size:.9rem}}.call{{border-left:4px solid var(--red);background:var(--redbg);padding:13px 16px}}table{{border-collapse:collapse;width:100%;min-width:680px}}.scroll{{overflow:auto;border:1px solid var(--line);border-radius:10px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code{{font-family:ui-monospace,monospace;background:#f0f4f6;padding:2px 4px;border-radius:4px;overflow-wrap:anywhere}}.cols{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}footer{{color:var(--muted);padding:10px 4px 24px;font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}.cols{{grid-template-columns:1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">M2.8 · 2026-10-01 · 10K 人口直接运行 · v4 运行记录</p><span class="badge">20 次调用超时 · 0 个可用回答</span><h1>GPU08 与模型正常启动；群体调用触发超时熔断</h1><p>完整 10K 组织配置已在 8 张 H20 上启动。模型端健康检查通过，但并发 16 下的首批请求超过 120 秒客户端时限，20 次请求均以网络/超时错误结算，驱动保留错误并停止派发。</p><nav aria-label="报告导航"><a href="#mapping">要求与证据</a><a href="#failure">运行结果</a><a href="#recovery">可恢复证据</a><a href="#next">下一版门槛</a></nav></header>
<div class="grid"><div class="metric"><b>235476 · COMPLETED</b><span>Slurm 08:29–08:37 · Exit 0</span></div><div class="metric"><b>8 × H20</b><span>GPU08 独占分配</span></div><div class="metric"><b>20 / 21,002</b><span>已尝试 / 计划调用</span></div><div class="metric"><b>0 / 9,980</b><span>可用回答 / 未尝试 worker</span></div></div>
<section id="mapping"><h2>用户要求、实现与证据</h2><div class="scroll"><table><thead><tr><th>要求</th><th>实施</th><th>实测证据</th><th>边界</th></tr></thead><tbody><tr><td>直接上 10K，不设单 Agent 成功前提</td><td>10,000 worker + 501 治理角色；两轮，21,002 槽位</td><td>群体驱动启动并写入完整计划；20 个 worker attempt</td><td>只完成首个 worker phase 的失败结算；治理阶段未开始</td></tr><tr><td>用 GPU08 全部资源和本地 DeepSeek</td><td>独占 8×H20；本地 SGLang 只监听 loopback</td><td>服务启动，08:32:16 health=200；Slurm 记录 gpu08 与 8 GPU</td><td>服务可用不代表该请求并发与时限组合可用</td></tr><tr><td>生产级记录、可恢复</td><td>receipt-first journal、预算、phase checkpoint</td><td>20 receipts、SQLite 备份 integrity=ok、worker phase checkpoint 已写共享目录</td><td>本次没有模型响应内容或用量；私人原始记录留在受限院内目录</td></tr></tbody></table></div></section>
<section id="failure"><h2>运行与故障证据</h2><p>Slurm 作业 <code>235476</code> 分配 GPU08 八张 H20、224 个 CPU，共运行 8 分 16 秒。应用摘要为 <code>halted=true</code>、<code>halt_reason=consecutive_transport_errors</code>。20 次结算均为 <code>network_or_timeout</code>，HTTP 状态未知；Usage 也未知，不能把它们计作零消耗。预算保留 20 次调用及 20,480 个最大输出 token 预留。</p><div class="call"><b>故障解释：</b>SGLang 日志记录请求生成结果到达时对应的 TokenizerManager 状态已删除；时间与 120 秒请求超时相符。因此“推理耗时超过时限”是强指向但仍属根因假设，需在后续运行验证。不能据此断言模型拒答或数学失败。</div><p>群体统计：20/21,002 个 planned slots 已有 attempt；20/20 未知 usage；9,980 个 worker 未尝试；首个 worker phase 后停止；observer/chief/global 均未开始。</p></section>
<section id="recovery"><h2>审计与恢复材料</h2><ul><li>实际 run summary、cycle checkpoint、progress、模型目录和完整 Slurm 输出均保留在院内运行目录。</li><li>GPU08 的本地 journal 与 budget 通过 SQLite backup 复制到共享存储；20 份 receipt 一并保存。Journal 完整性检查返回 <code>ok</code>。</li><li>Journal SHA-256：<code>{e['evidence']['journal_sha256']}</code>；源码 commit：<code>{e['source_commit']}</code>；源码归档 SHA-256：<code>{e['source_archive_sha256']}</code>。</li><li>容器 SHA-256：<code>{e['model']['container_sha256']}</code>；模型 config SHA-256：<code>{e['model']['model_config_sha256']}</code>。用户/模型响应正文未发布到公共 GitHub。</li></ul><p>该 10K 人口运行没有产生数学结论，没有证明 Navier–Stokes 命题，也没有测量或支持某种 Agent 架构优越性。</p></section>
<section id="next"><h2>下一版要完成的工程设计</h2><div class="cols"><div><h3>已实现</h3><ul><li>10K 组织与 501 个治理角色直接初始化。</li><li>无单 Agent 成功门槛、无 N8/N32/N128 阶梯要求。</li><li>断点数据、20 份收据和失败原因已保存。</li></ul></div><div><h3>下一版开跑前</h3><ul><li>根据八卡实测吞吐，联合设定并发、调用超时、每次输出上限和 8h30m Slurm 时限。</li><li>固定新的 run ID、配置哈希和来源 commit；不得恢复后伪称为独立 replicate。</li><li>先核对最早请求的完成时延与服务端生成速度，再判断直接提交完整人口的可行预算。</li></ul></div></div><p><b>就绪度：</b>架构可继续设计；运行配置需要更新；当前 v4 不可恢复为新 profile。下一轮仍按完整 10K 组织实验推进。</p></section><footer>记录快照：{e['snapshot_time']} · 本报告区分工程运行证据与数学验证。失败 attempts、timeout 和未知用量均保留。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{let n=document.querySelector(a.getAttribute('href'));if(n)n.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
(ROOT/'milestones/m2-8-direct-10k-gpu08-v4-attempt-v1.html').write_text(page)
print(ROOT/'milestones/m2-8-direct-10k-gpu08-v4-attempt-v1.html')
