#!/usr/bin/env python3
"""Render a self-contained launch-status HTML from its versioned evidence JSON."""
import html, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'milestones/m2-8-direct-10k-launch-v1.json'
OUT = ROOT / 'milestones/m2-8-direct-10k-launch-v1.html'
e = json.loads(DATA.read_text())
esc = html.escape
requirements = [
    ('10K 群体，不设单 Agent 成功门槛', '100 组 × 100 分析 Agent，另设 501 个治理角色；两轮，21,002 调用槽。', '已冻结并提交；执行数仍为 0。'),
    ('在 GPU08 用可验证的本地 DeepSeek', '8 张 H20 独占分配；复用已验收的权重与镜像，FP8/JIT 设置按此前成功配置。', 'Slurm RUNNING；权重 48/48 已读；健康检查未通过。'),
    ('过程可追溯、可复现', '源码 commit、配置、source archive、模型身份、Slurm 身份及原始日志保留。', '源码包哈希与模型/镜像 SHA-256 已记录；私有逐请求证据将在集群目录落盘。'),
    ('数学结果可核验', 'Navier–Stokes 候选、异议和证明义务均按未验证状态留存。', '尚未收到数学输出；本次运行不能单独证明任何结论。')]
rows = ''.join('<tr>'+''.join(f'<td>{esc(v)}</td>' for v in r)+'</tr>' for r in requirements)
limits = ''.join(f'<li>{esc(v)}</li>' for v in e['limitations'])
settings = ''.join(f'<li><code>{esc(v)}</code></li>' for v in e['model']['settings'])
html_doc = f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(e['milestone'])} · {esc(e['version'])}</title><style>
:root{{--ink:#182733;--muted:#586b78;--line:#d6e0e7;--paper:#fff;--wash:#f3f7f8;--amber:#754c08;--amberbg:#fff4d8;--green:#126449}}*{{box-sizing:border-box}}body{{margin:0;background:#edf2f4;color:var(--ink);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}a{{color:#075d91}}.wrap{{max-width:1100px;margin:24px auto;padding:0 18px}}header,section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:24px 28px;margin:14px 0}}header{{background:linear-gradient(125deg,#fff 50%,#fff7e5)}}h1{{font-size:clamp(1.8rem,4vw,2.6rem);line-height:1.2;margin:.4rem 0}}h2{{font-size:1.25rem;margin:0 0 12px}}.muted{{color:var(--muted)}}.status{{display:inline-block;background:var(--amberbg);color:var(--amber);border-radius:99px;padding:5px 12px;font-weight:700}}nav{{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}}nav a{{background:white;border:1px solid var(--line);border-radius:99px;padding:6px 10px;text-decoration:none;color:var(--ink)}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.metric{{border:1px solid var(--line);border-radius:12px;padding:14px;background:#fff}}.metric b{{display:block;font-size:1.25rem}}.metric span{{font-size:.9rem;color:var(--muted)}}.table{{overflow:auto;border:1px solid var(--line);border-radius:10px}}table{{border-collapse:collapse;width:100%;min-width:720px}}th,td{{text-align:left;vertical-align:top;padding:11px;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}tr:last-child td{{border-bottom:0}}code,pre{{font-family:ui-monospace,monospace;overflow-wrap:anywhere}}code{{background:#f0f4f6;padding:2px 4px;border-radius:4px}}.call{{border-left:4px solid #b88718;background:var(--amberbg);padding:12px 15px}}.two{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}footer{{padding:8px 4px 24px;color:var(--muted);font-size:.9rem}}@media(max-width:740px){{.wrap{{padding:0 10px;margin:10px auto}}header,section{{padding:20px 16px}}.grid{{grid-template-columns:1fr 1fr}}.two{{grid-template-columns:1fr}}}}@media(max-width:420px){{.grid{{grid-template-columns:1fr}}}}@media print{{body{{background:#fff;font-size:11pt}}.wrap{{max-width:none;margin:0;padding:0}}header,section{{box-shadow:none;break-inside:avoid}}nav{{display:none}}a{{color:inherit}}}}
</style></head><body><main class="wrap"><header><p class="muted">{esc(e['milestone'])} · {esc(e['version'])} · {esc(e['snapshot_time'])}</p><span class="status">GPU08 作业运行中 · 模型初始化中</span><h1>直接提交 10K 群体：首轮运行已取得 GPU08</h1><p>{esc(e['outcome'])}</p><nav aria-label="报告导航"><a href="#requirements">需求映射</a><a href="#run">运行与资源</a><a href="#evidence">证据与来源</a><a href="#limits">边界与下一步</a></nav></header>
<div class="grid" aria-label="关键状态"><div class="metric"><b>10,000</b><span>分析 Agent</span></div><div class="metric"><b>501</b><span>治理角色</span></div><div class="metric"><b>8 × H20</b><span>GPU08 独占分配</span></div><div class="metric"><b>0 / 21,002</b><span>截至快照模型调用</span></div></div>
<section id="requirements"><h2>用户要求 → 实现 → 当前证据</h2><div class="table"><table><thead><tr><th>要求</th><th>实现</th><th>实际证据 / 状态</th></tr></thead><tbody>{rows}</tbody></table></div></section>
<section id="run"><h2>Slurm 与模型启动快照</h2><div class="two"><div><p><b>作业：</b><code>{esc(e['slurm']['job_id'])}</code> · <b>状态：</b>{esc(e['slurm']['state'])} · <b>节点：</b>{esc(e['slurm']['node'])}</p><p><b>分配：</b>{esc(e['slurm']['allocated_gpus'])}，独占；Slurm 将整节点的 224 CPU/内存记入 AllocTRES。</p><p><b>模型：</b>{esc(e['model']['name'])}，{esc(e['model']['load_progress'])}</p><ul>{settings}</ul></div><div><p><b>组织：</b>100 组 × 100 worker + 400 Observer + 100 group Chief + 1 global Chief。</p><p><b>循环与并发：</b>2 轮；21,002 planned call slots；最多 16 个在途调用。</p><p><b>冻结源码：</b><code>{esc(e['source_baseline_commit'])}</code></p><p class="call">当前只确认取得 GPU 与载入权重。模型健康检查尚未通过，驱动未发送数学或人口请求。按冻结上限，模型初始化最多等待 30 分钟。</p></div></div></section>
<section id="evidence"><h2>可追溯身份</h2><ul><li>容器 SHA-256：<code>{esc(e['model']['container_sha256'])}</code></li><li>模型配置 SHA-256：<code>{esc(e['model']['model_config_sha256'])}</code></li><li>提交源码归档 SHA-256：<code>{esc(e['source_archive_sha256'])}</code></li><li>源码：<a href="../docs/direct-10k-gpu08-v3.md">冻结执行说明</a> · <a href="../examples/slcw-direct-10k-gpu08-v3.json">运行配置</a> · <a href="../cluster/direct-10k-gpu08-v3.sbatch">Slurm 脚本</a></li><li>完整模型与 Slurm 日志、每次请求和恢复点保存在集群受限运行目录，不将原始响应上传到公开仓库。</li></ul></section>
<section id="limits"><h2>解释边界与后续门槛</h2><ul>{limits}</ul><p><b>当前状态：</b>设计与实现已就绪；运行已提交；模型服务尚未就绪；数学评价与组织效果无结论。</p><p><b>下一步：</b>等待本地服务健康检查，然后核验首批实际调用、请求预算和事件/回执记录；如果技术停止被触发，保留已有失败和未启动分母，另出新版 HTML 记录结果。</p></section><footer>此报告是截至快照时间的运行状态记录；它不是最终群体结果，也不代表数学证明或组织优越性。</footer></main><script>document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{{const el=document.querySelector(a.getAttribute('href'));if(el)el.scrollIntoView({{behavior:'smooth'}})}}));</script></body></html>'''
OUT.write_text(html_doc)
print(OUT)
